# Generated by Django 6.0.6 on 2026-08-05 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_donation_details_and_more'),
        ('members', '0004_member_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['association', 'registration_date'], name='members_mem_associa_bab0d7_idx'),
        ),
    ]
