# Generated by Django 6.0.6 on 2026-09-05 03:31

import apps.members.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_members_mem_associa_bab0d7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='indigene_image',
            field=models.ImageField(blank=True, help_text='Used only by association administrators to verify indigene status before approval. Deleted automatically once the application is approved.', null=True, upload_to='members/indigene/%Y/%m/', validators=[apps.members.validators.MaxFileSizeValidator(max_mb=5)]),
        ),
    ]
