# Generated by Django 6.0.6 — v1.2 Communication Center

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_type', models.CharField(choices=[('all', 'All Members'), ('approved', 'Approved Members'), ('pending', 'Pending Members'), ('faculty', 'Faculty'), ('department', 'Department'), ('level', 'Level'), ('gender', 'Gender'), ('selected', 'Selected Members'), ('custom', 'Custom Filter')], max_length=20)),
                ('recipient_filters', models.JSONField(blank=True, default=dict)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS (Coming Soon)'), ('push', 'Push Notification (Coming Soon)')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='How many members matched the targeting at send time.')),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.association')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
                'permissions': [('send_announcement', 'Can access the Communication Center and send announcements')],
            },
        ),
    ]
