# Generated by Django 6.0.6 on 2026-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_donation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='aims',
            field=models.TextField(blank=True, help_text="The association's aims, as stated in its constitution — one per line. Shown as a bulleted list on the About page. Kept distinct from Mission/Vision: a constitution's 'Aims' section is its own category, not necessarily equivalent to either, so this exists rather than forcing that content into a field with a different meaning."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_info',
            field=models.TextField(blank=True, help_text='Who can join and any membership conditions, as stated in the constitution — shown on the About page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='objectives',
            field=models.TextField(blank=True, help_text="The association's objectives, as stated in its constitution — one per line. Shown as a bulleted list on the About page."),
        ),
    ]
