# Generated by Django 6.0.6 on 2026-08-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_agedistributionsnapshot_age_bracket'),
        ('core', '0002_sitesettings_donation_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(help_text='Calendar date of the visit, for indexed date-range filtering.')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('page_key', models.CharField(help_text="Resolved URL name (e.g. 'core:home', 'elections:election_detail'), not the raw path.", max_length=100)),
                ('path', models.CharField(help_text='Raw request path, for reference only.', max_length=255)),
                ('visitor_hash', models.CharField(help_text='One-way HMAC of IP+User-Agent+day. Never the raw IP.', max_length=64)),
                ('visitor_type', models.CharField(choices=[('anonymous', 'Anonymous'), ('member', 'Authenticated Member')], default='anonymous', max_length=10)),
                ('device_category', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('browser_category', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('edge', 'Edge'), ('safari', 'Safari'), ('other', 'Other')], default='other', max_length=10)),
                ('referrer_category', models.CharField(choices=[('direct', 'Direct'), ('search', 'Search Engine'), ('social', 'Social Media'), ('other_website', 'Other Website'), ('unknown', 'Unknown')], default='unknown', max_length=15)),
                ('association', models.ForeignKey(blank=True, help_text='Null if no association is configured yet at request time.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='core.association')),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'permissions': [('view_visitor_analytics', 'Can view the visitor analytics dashboard')],
                'indexes': [models.Index(fields=['visit_date'], name='pv_visit_date_idx'), models.Index(fields=['association', 'visit_date'], name='pv_assoc_date_idx'), models.Index(fields=['association', 'visit_date', 'page_key'], name='pv_assoc_date_page_idx'), models.Index(fields=['association', 'visit_date', 'device_category'], name='pv_assoc_date_device_idx'), models.Index(fields=['association', 'visit_date', 'browser_category'], name='pv_assoc_date_browser_idx'), models.Index(fields=['association', 'visit_date', 'referrer_category'], name='pv_assoc_date_referrer_idx')],
            },
        ),
    ]
